### PR TITLE
added cats and dogs training data as zip

### PR DESCRIPTION
**Pull request by deki**
The CatDogRecognition sample in jsr381-examples uses zip. There is no easy way to use the existing rar file in Java without a third party library that's why I think it makes more sense to add this one here.

### CODE REVIEW

**Comment by deki** [comment]
@nishantraut please let me know if you prefer a different approach

**Comment by nishantraut** [comment]
@deki thank you for fixing this issue.

**Comment by deepnetts** [comment]
Replaced rar with zip

**Comment by fgreco55** [comment]
> The CatDogRecognition sample in jsr381-examples uses zip. There is no easy way to use the existing rar file in Java without a third party library that's why I think it makes more sense to add this one here.

@deki Hey Dennis... I encountered the same problem.  Thanks for the fix!

**Pull request merged**
